// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} tableName
 * @returns {$CancellablePromise<boolean>}
 */
export function IsTableEmpty(tableName) {
    return $Call.ByID(2463382050, tableName);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SetupOfflineCrossReferences() {
    return $Call.ByID(1235067543);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function UpgradeMannaApp() {
    return $Call.ByID(1484749673);
}
